[package]
name = "citro2d-sys"
version = "0.2.0"
edition = "2024"
links = "citro2d"

[dependencies]
libc = "0.2"
ctru-sys = { git = "https://github.com/rust3ds/ctru-rs.git" }
citro3d-sys = { git = "https://github.com/rust3ds/citro3d-rs.git" }

[build-dependencies]
bindgen = { version = "0.72", features = ["experimental"] }
cc = "1.0"
doxygen-rs = "0.4.2"

[dev-dependencies]
shim-3ds = { git = "https://github.com/rust3ds/shim-3ds.git" }
